#!/usr/bin/env bash
# Assemble the GitHub Pages site content under build/gh-pages.
# Published with the built-in Actions-based Pages deployment (no PAT needed).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

SITE="$BUILD_DIR/gh-pages"
rm -rf "$SITE"
mkdir -p "$SITE/apt" "$SITE/dnf"

cp -r "$REPOSITORY_DIR/apt/." "$SITE/apt/"
cp -r "$REPOSITORY_DIR/dnf/." "$SITE/dnf/"

# Checksums for the direct downloads (generated by the release workflow).
[ -f "$PACKAGES_DIR/SHA256SUMS" ] && cp "$PACKAGES_DIR/SHA256SUMS" "$SITE/SHA256SUMS"

cat > "$SITE/index.html" <<'HTML'
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Retro TV - Downloads</title>
<style>
body{font-family:system-ui,sans-serif;max-width:760px;margin:2rem auto;padding:0 1rem;line-height:1.5}
code{background:#f4f4f4;padding:2px 5px;border-radius:4px}
pre{background:#f4f4f4;padding:1rem;border-radius:6px;overflow-x:auto}
</style>
</head>
<body>
<h1>Retro TV</h1>
<p>Retro-styled IPTV / YouTube streaming TV app (Linux, amd64).</p>
<p>Homepage / source: <a href="https://github.com/mzainulabideendev/Retro-TV">github.com/mzainulabideendev/Retro-TV</a></p>

<h2>APT (Debian / Ubuntu / Mint)</h2>
<pre>
sudo install -d -m 0755 /etc/apt/keyrings
curl -fsSL https://mzainulabideendev.github.io/Retro-TV/apt/retro-tv-archive-keyring.gpg | sudo tee /etc/apt/keyrings/retro-tv-archive-keyring.gpg &gt;/dev/null
echo "deb [signed-by=/etc/apt/keyrings/retro-tv-archive-keyring.gpg] https://mzainulabideendev.github.io/Retro-TV/apt stable main" | sudo tee /etc/apt/sources.list.d/retro-tv.list &gt;/dev/null
sudo apt update
sudo apt install retro-tv
</pre>

<h2>DNF (Fedora)</h2>
<pre>
sudo curl -fsSL https://mzainulabideendev.github.io/Retro-TV/dnf/REPO-METADATA-PUBLIC-KEY.asc -o /etc/pki/rpm-gpg/RPM-GPG-KEY-retro-tv
printf '[retro-tv]\nname=Retro TV\nbaseurl=https://mzainulabideendev.github.io/Retro-TV/dnf/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-retro-tv\n' | sudo tee /etc/yum.repos.d/retro-tv.repo
sudo dnf install retro-tv
</pre>

<h2>Arch Linux (build from source)</h2>
<p>The Arch PKGBUILD builds the tagged source and needs Flutter 3.47.2 on your PATH.</p>
<pre>
sudo pacman -S --needed base-devel git gtk3 mpv gcc-libs clang cmake ninja patchelf
mkdir -p "$HOME/.local/opt"
curl -fL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.47.2-stable.tar.xz -o /tmp/flutter-linux.tar.xz
tar -xJf /tmp/flutter-linux.tar.xz -C "$HOME/.local/opt"
export PATH="$HOME/.local/opt/flutter/bin:$PATH"
mkdir -p "$HOME/src/retro-tv" &amp;&amp; cd "$HOME/src/retro-tv"
curl -fsSL https://raw.githubusercontent.com/mzainulabideendev/Retro-TV/v1.2.3/packaging/arch/PKGBUILD -o PKGBUILD
makepkg -si
</pre>

<h2>Direct downloads</h2>
<ul>
HTML

for f in "$SITE/apt"/pool/main/r/retro-tv/*.deb "$SITE/dnf"/*.rpm; do
    [ -f "$f" ] || continue
    b="$(basename "$f")"
    if [[ "$b" == *.deb ]]; then rel="apt/pool/main/r/retro-tv/$b"; else rel="dnf/$b"; fi
    printf '<li><a href="%s">%s</a></li>\n' "$rel" "$b" >> "$SITE/index.html"
done

echo '<li><a href="SHA256SUMS">SHA256SUMS</a></li>' >> "$SITE/index.html"

cat >> "$SITE/index.html" <<'HTML'
</ul>
<p>Flatpak bundles are attached to <a href="https://github.com/mzainulabideendev/Retro-TV/releases">GitHub Releases</a>.</p>
</body>
</html>
HTML

log "gh-pages content ready at $SITE"
du -sh "$SITE"